services:
  redis:
    image: redis:7.2.4-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"

  backend:
    build:
      context: ./backend
      args:
        - BUILD_VERSION=${BUILD_VERSION:-dev}
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    environment:
      - DATABASE_URL=sqlite:////data/db/arbitrage.db
      - REDIS_URL=redis://redis:6379/0
      - CONFIG_FILE_PATH=/config/default.yaml
    volumes:
      - ./backend:/app
      - ./db:/data/db
      - ./config:/config
    ports:
      - "8000:8000"
    depends_on:
      - redis

  worker:
    build:
      context: ./worker
    environment:
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - ./worker:/app
    depends_on:
      - redis

  frontend:
    build:
      context: ./frontend
    environment:
      - NEXT_PUBLIC_WS_URL=ws://backend:8000/ws/stream
      - NEXT_PUBLIC_API_URL=http://backend:8000
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes: {}
